import type { Metadata } from "next";
import { Jacquarda_Bastarda_9 } from "next/font/google";
import "./globals.css";

const jBastarda9Font = Jacquarda_Bastarda_9({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-jacquarda-bastarda-9",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jBastarda9Font.className}`}
      >
        {children}
      </body>
    </html>
  );
}
